name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: azhi
    - name: 构建镜像
      run: docker build -t hongz1125/cicd-web .
      
    - name: 推送镜像
      run: docker push hongz1125/cicd-web
