name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 构建镜像
      run: docker build -t hongz1125/cicd-web .
      
    - name: 登录
      run: docker login -u hongz1125 -p dckr_pat_57oSYtP8q6EJBVry754mvemqytg
    
    - name: 推送
      run: docker push hongz1125/cicd-web
